name: inject_generator
version: 1.0.0-alpha
description: Dev-time dependency for package:inject.
authors:
  - Matan Lurey <matanl@google.com>
  - Yegor Jbanov <yjbanov@google.com>
homepage: https://pub.dartlang.org/packages/inject

environment:
  sdk: '>=2.0.0 <3.0.0'

dependencies:
  analyzer: '>= 0.32.4 <0.37.0'
  build: '>=0.12.6 <1.2.0'
  code_builder: '>=3.1.3 <3.3.0'
  collection: ^1.14.7
  dart_style: '>= 1.0.0 <1.3.0'
  logging: ^0.11.3+1
  meta: ^1.1.7
  path: ^1.6.2
  quiver: ^2.0.2
  stack_trace: ^1.9.3

dev_dependencies:
  build_runner: '>=0.10.3 <1.4.0'
  build_test: ^0.10.7
  inject:
    path: ../inject
  test: ^1.6.2
